### ISSUE TITLE
Feature request:  add support for context.Context

### ISSUE THREAD

**Issue by wuman** [garyburd/redigo#207] opened 2016-10-05 17:57 UTC
The use of `context.Context` is recommended for cancellation and deadlines.  It would be helpful if redigo could support `context.Context` and be able to cancel early when needed.

**Comment by garyburd** [comment] 2016-10-05 18:12
Please given an examples of where you will use this feature.

**Comment by wuman** [comment] 2016-10-06 13:37
A good example would be how the library https://godoc.org/github.com/cihangir/ctxdb adds support for `context.Context` to the `sql` package in standard golang.

With support for context, one can probably call a function implemented like the following:
```
func PingRedis(ctx context.Context) {
    c, _ := redis.Dial(ctx, "tcp", server)
    c.Do(ctx, "PING")
}
```
And when the caller cancels the context, any redis calls would be cancelled to save resources.

**Comment by elithrar** [comment] 2016-10-06 13:38
How would you implement this in a useful way without breaking the existing
API?

**Comment by garyburd** [comment] 2016-10-06 15:09
@wuman I am asking for real examples of where you need the feature, not examples of other packages that have a similar feature.

Canceling a single `Do()` call will not save significant resources. The implementation is likely to increase the time and memory costs of executing the call.

**Comment by clutchski** [comment] 2016-10-12 20:32
@garyburd instrumentation is a common case for contexts. if redigo allowed a context argument it would be trivial for other folks (like me :) to add redigo wrappers which add code tracing, which let you connect redis network calls with the web request they came from etc. this is extremely common in dapper style instrumentation (like zipkin, opentracing, etc)

context: I work at datadog and am looking to add tracing to our use of redigo.

**Comment by garyburd** [comment] 2016-10-13 15:31
@clutchski Assuming that the following are added, is there enough for you to implement your instrumentation wrapper?  Do you need to know anything about the underlying connection?

    type ConnContext interface {
        Close() error
        Err() error
        Do(ctx context.Context, commandName string, args ...interface{}) (reply interface{}, err error)
        Send(ctx context.Context, commandName string, args ...interface{}) error
        Flush(ctx context.Context) error
        Receive(ctx context.Context) (reply interface{}, err error)
    }

    type ContextConnAdapter struct {
        redis.Conn
    }
 
    func (cc Context.Conn)  Do(ctx context.Context, commandName string, args ...interface{}) (reply interface{}, err error)  {
        return cc.Conn.Do(commandName, args...)
    }

    ... and similar methods for Send, Flush, Receive.

**Comment by clutchski** [comment] 2016-10-17 16:31
@garyburd let me play with it and i will get back to you.

**Comment by garyburd** [comment] 2016-10-26 22:02
There is a way to save resources on a canceled command without increasing the resources used for all commands. The receive function can skip allocating the response data. The receive function will still need to wait for the the response from the server and parse the response.  Is this an important savings?

**Comment by garyburd** [comment] 2016-11-28 19:55
I am closing this issue because there's not a specific application problem to be fixed. 

If you are having a problem with Redigo with your application, then open a new issue describing the problem.  Adding support for context.Context is a possible fix for a problem, it's not a description of the problem.

**Closed by garyburd** 2016-11-28 19:55 UTC

**Comment by wyattjoh** [comment] 2017-03-02 21:34
Hi @garyburd, my use case is this:

I need to better handle a job processor which uses the Redis command `BLPOP` to pull queue items off a list.

I can add a timeout, which would cause the application to keep cycling between two different states (timeout and check if shutdown) whereas if I could pass context in with a cancellation, then when the context is canceled, the blocking request would be canceled then and there and the goroutine could end gracefully.

Any feedback is appreciated.

**Comment by garyburd** [comment] 2017-03-02 23:24
@wyattjoh It is not burdensome to check for timeout and done in the application:

    func blpop(ctx context.Context, c redis.Conn, key string) ([]byte, error) {
        for {
            select {
            case <-ctx.Done():
                return nil, nil
            default:
                resp, err := redis.ByteSlices(c.Do("BLPOP", key, 5))
                if err == redis.ErrNil {
                    continue
                }
                if err != nil {
                    return nil, err
                }
                return resp[1], nll
            }
        }
    }

**Comment by wyattjoh** [comment] 2017-03-02 23:40
The downside here is that once the context is canceled, I may have to wait up to 5 seconds before the function actually exits.

**Comment by garyburd** [comment] 2017-03-03 02:47
@wyattjoh If you want the caller of the function to return immediately on cancel or pop from the list, then wrap the for loop above in a goroutine that sends the result to a channel. Select on that channel and ctx.Done().

**Comment by wyattjoh** [comment] 2017-03-03 04:45
The issue is that the `BLPOP` would pull something out of the list (out of the queue), and during a shutdown, it would mean that there would be the possibility of a result being discarded.

At the moment, my current solution just waits the 5 seconds, which gives guarantees that nothing is pulled from the queue that isn't processed then afterwards.

**Comment by garyburd** [comment] 2017-03-03 05:03
There are three ways that receive on the BLPOP result will exit:  the command times out, the command returns a result, the underlying network connection is closed. Closing the connection will not work for you because you don't want to lose values. That leaves the two options used in my proposed function above.

Passing a context to Do opens the possibility of adding the functionality to the connection instead of the application, but it does not change what the options are.

If your application does not want to lose values, then the application must wait for the command timeout on cancel.

**Comment by wyattjoh** [comment] 2017-03-03 05:38
That works for me, I was under the assumption that we could just terminate the connection without causing any issues with Redis, but I stand corrected.

Thanks for the information!

**Comment by johnwchadwick** [comment] 2017-08-10 12:02
A legitimate use where context would be nice is for Receive, which right now is definitely painful if you need the ability to cancel.

**Comment by johanbrandhorst** [comment] 2017-08-23 08:33
I'd also like to see a context parameter for `PubSubConn.Recieve`. It's becoming more and more idiomatic to have use context for cancellation, especially if the function is blocking.

**Comment by jchv** [comment] 2017-08-23 10:47
I'm beginning to feel like the Go language needs to address cancellation. I can see why package maintainers don't want to introduce context versions of everything.

Currently, one possible solution that requires no modification of the library is to use `NewConn` and then use `DialContext` for the underlying connection. I haven't tested it thoroughly, but in theory it will do what you want when you cancel the context.

**Comment by johanbrandhorst** [comment] 2017-08-23 10:59
@jchv that would cancel the entire connection though, when one might just want to be able to cancel the `Receive` call without disrupting other users of the connection.

**Comment by garyburd** [comment] 2017-08-23 14:54
@jchv Describe the application scenario where you want to cancel `Receive`.

@johanbrandhorst  To cancel an application message receive loop, unsubscribe the connection ([psc.Unsubscribe()](https://godoc.org/github.com/garyburd/redigo/redis#PubSubConn.Unsubscribe) or [psc.PUnsubscribe()](https://godoc.org/github.com/garyburd/redigo/redis#PubSubConn.PUnsubscribe) depending on how app subscribes) and exit the loop when the number channels is zero ([v.Count](https://godoc.org/github.com/garyburd/redigo/redis#Subscription.Count) == 0).

**Comment by jchv** [comment] 2017-08-23 16:15
@garyburd The main use case is when exiting the application. Occasionally, I have Redis pubsub connections that directly stem from user requests (like long-running websockets,) so those are also cases where I'd like to be able to cancel.

I'm also subscribing to a very large number of channels (sometimes >10000,) so I'd rather avoid unsubscribing every channel at the end. I am not aware of a good reason why closing the socket wouldn't work here, so that's pretty much what I'm doing.

In a vaccuum, it's reasonable to just quit the application and let the OS clean things up. However, I mostly just want to kill the pubsub loop so that it doesn't call into other code that's being uninitialized, which leads to sporadic issues. Other code may have greater consistency requirements and it would be better to shut down gracefully, so this is important.

@johanbrandhorst I don't think you can reasonably use a Redis connection for anything after you've began subscribing to pubsub channels, so I don't think that is a problem.

**Comment by garyburd** [comment] 2017-08-23 17:30
@jchv Unsubscribing the connection is the clean way to cancel application pubsub receive loops. It's at most two commands (one for channels, one for patterns).

The server must cleanup the subscriptions one way or another. Closing the connection directly will not save the server from doing this work.

**Comment by jchv** [comment] 2017-08-24 20:18
Oh - I did not know those two things. I actually didn't realize you could call UNSUBSCRIBE with no arguments. Well, that answers my questions. Thanks a lot for your time.
