### ISSUE TITLE
PubSubConn.Receive blocks without returning any error

### ISSUE THREAD

**Issue by nvartolomei** [garyburd/redigo#190] opened 2016-07-25 10:28 UTC
Anyone had this behavior? I calling `Receive` method in a for loop. And it blocks for some reasons without any error, and doesn't listen return new messages.

**Comment by nvartolomei** [comment] 2016-07-25 10:49
* This behavior is observed in kubernetes environment.

**Comment by garyburd** [comment] 2016-07-25 13:40
Please describe how to reproduce this issue.

**Comment by nvartolomei** [comment] 2016-07-25 13:51
Unfortunately I wasn't able to reproduce this issue locally. 
The code looks like this:

```
conn := pool.Get()
pubSubConn = redis.PubSubConn{Conn: conn}


conn := pool.Get()
pubSubConn = redis.PubSubConn{Conn: conn}

for {
    switch redisMsg := pubSubConn.Receive().(type) {
    case redis.Message:
      if err := json.Unmarshal(redisMsg.Data, &m); err != nil {
        log.Errorf("Error parsing pubsub message: %v", err)
        continue
      }

      log.Infof("Got message: %v", m.Topic)

    case error:
      panic(fmt.Sprintf("Error while waiting for message from pubsub: %v", redisMsg))

    default:
      // @TODO(nv): remove this
      log.Infof("unexpected pubsub message: %v", redisMsg)
    }
  }
```

And after some time (hours-days) I don't observe any new `Got message: %v` messages in my log. Not sure where to start investigating this, but maybe I'm lucky and someone smarter than me had the same issue :/

**Comment by garyburd** [comment] 2016-07-25 14:08
Show the code that subscribes the connection to a Redis channel.

**Comment by nvartolomei** [comment] 2016-07-25 14:21
The code is in my last comment.

**Comment by garyburd** [comment] 2016-07-25 14:26
I don't see code that subscribes to a channel.  
What is package redisurl?

**Comment by nvartolomei** [comment] 2016-07-25 14:34
@garyburd updated my comment. redisurl is https://github.com/soveran/redisurl.

**Comment by garyburd** [comment] 2016-07-25 15:26
The posted code looks OK. 

Have you looked at the publisher? Is it still running and publishing to the same channel and instance of Redis?

Unrelated to this issue, is there a reason why you are using redisurl instead of [DialURL](https://godoc.org/github.com/garyburd/redigo/redis#DialURL)?

**Comment by nvartolomei** [comment] 2016-07-25 15:52
The publisher is ok, as I receive messages if trying to subscribe via redis-cli. I think dialurl wasn't there when this code was initially written.

I written some logic to send pings and connect with read timeout for now. I'll try to reproduce this issue later and see the netstat output too.

**Comment by garyburd** [comment] 2016-07-25 21:56
I am closing because there's nothing to act on now.  Open a new issue when you can provide info on how to reproduce the problem.

**Closed by garyburd** 2016-07-25 21:56 UTC
